Copyright **`(c)`** 2023 Giovanni Squillero `<giovanni.squillero@polito.it>`  
[`https://github.com/squillero/computational-intelligence`](https://github.com/squillero/computational-intelligence)  
Free for personal or classroom use; see [`LICENSE.md`](https://github.com/squillero/computational-intelligence/blob/master/LICENSE.md) for details.  

# LAB10

Use reinforcement learning to devise a tic-tac-toe player.

### Deadlines:

* Submission: Sunday, December 17 ([CET](https://www.timeanddate.com/time/zones/cet))
* Reviews: Dies Natalis Solis Invicti ([CET](https://en.wikipedia.org/wiki/Sol_Invictus))

Notes:

* Reviews will be assigned  on Monday, December 4
* You need to commit in order to be selected as a reviewer (ie. better to commit an empty work than not to commit)

In [228]:
import numpy as np
from collections import namedtuple

[4,9,2]
[3,5,7]
[8,1,6]

In [229]:
Tikly = namedtuple("Tikly", "row, column")

class TikTakToe():
    def __init__(self):
        self.board = np.zeros(9)
        self.mask = np.array([4,9,2,3,5,7,8,1,6])
        self.player = 1
        self.winner = None

    def move(self, position : Tikly) -> bool:
        position = position.row * 3 + position.column
        if self.board[position] == 0:
            self.board[position] = self.player #* self.mask[position]
            self.player = -self.player
            return True
        else:
            return False

    def possible_moves(self) -> list:
        return [Tikly(i//3, i%3) for i in range(9) if self.board[i] == 0]

    def check_finished(self) -> bool:
        if np.sum(self.board == 0) == 0 or self.check_winner() != 0:
            return True
        else:
            return False 

    def check_winner(self) -> int:
        board = self.board.reshape(3,3)
        for i in range(3):
            if np.sum(board[i,:]) == 3 or np.sum(board[:,i]) == 3:
                return 1
            elif np.sum(board[i,:]) == -3 or np.sum(board[:,i]) == -3:
                return -1
        if np.sum(np.diag(board)) == 3 or np.sum(np.diag(np.fliplr(board))) == 3:
            return 1
        elif np.sum(np.diag(board)) == -3 or np.sum(np.diag(np.fliplr(board))) == -3:
            return -1
        else:
            return 0        

    def __str__(self):
        return f"Player to move : {self.player}"+ "\n" + str(self.board.reshape(3,3))
    
    def __repr__(self):
        return str(self.board)

In [230]:
class Player():
    def __init__(self, k : int = None):
        self.k = k

    def play(self,board : np.array) -> Tikly :
        pass

In [231]:
class RandomPlayer(Player):
    def __init__(self):
        super().__init__()

    def play(self, board : TikTakToe) -> Tikly:
        possible_moves = board.possible_moves()
        move = possible_moves[np.random.randint(len(possible_moves))]
        return move

In [232]:
class HumanPlayer(Player):
    def __init__(self):
        super().__init__()

    def play(self, board : TikTakToe) -> Tikly:
        possible_moves = board.possible_moves()
        print("Possible moves : ", possible_moves)
        row = input("Row : ")
        column = input("Column : ")
        move = Tikly(row, column)
        return move

In [233]:
board = TikTakToe()
possible_moves = np.where(board.board == 0)
print(possible_moves)

(array([0, 1, 2, 3, 4, 5, 6, 7, 8]),)


In [234]:
board = TikTakToe()
possible_moves = np.where(board.board == 0)
print(possible_moves)

(array([0, 1, 2, 3, 4, 5, 6, 7, 8]),)


In [235]:
board = TikTakToe()
board.move(Tikly(0,0))
board.move(Tikly(1,1))
board.move(Tikly(0,1))
board.move(Tikly(1,2))
board.move(Tikly(0,2))
board.check_winner()

1

In [236]:
board = TikTakToe()
player = [RandomPlayer(), RandomPlayer()]
i = 0
while not board.check_winner():
    board.move(player[i].play(board))
    i = 1 - i
    print(board)
print(f"Winner Winner : player {(board.check_winner() + 1)//2}" )

Player to move : -1
[[0. 0. 1.]
 [0. 0. 0.]
 [0. 0. 0.]]
Player to move : 1
[[ 0.  0.  1.]
 [ 0.  0. -1.]
 [ 0.  0.  0.]]
Player to move : -1
[[ 0.  0.  1.]
 [ 0.  1. -1.]
 [ 0.  0.  0.]]
Player to move : 1
[[ 0.  0.  1.]
 [ 0.  1. -1.]
 [ 0. -1.  0.]]
Player to move : -1
[[ 0.  1.  1.]
 [ 0.  1. -1.]
 [ 0. -1.  0.]]
Player to move : 1
[[ 0.  1.  1.]
 [-1.  1. -1.]
 [ 0. -1.  0.]]
Player to move : -1
[[ 0.  1.  1.]
 [-1.  1. -1.]
 [ 0. -1.  1.]]
Player to move : 1
[[-1.  1.  1.]
 [-1.  1. -1.]
 [ 0. -1.  1.]]
Player to move : -1
[[-1.  1.  1.]
 [-1.  1. -1.]
 [ 1. -1.  1.]]
Winner Winner : player 1
